-- Active: 1687050745119@@127.0.0.1@5432@Hesap-eProject@public
-- Generated by the database client, not guaranteed complete.
CREATE TABLE admin(
    id SERIAL NOT NULL,
    username character varying,
    password character varying,
    PRIMARY KEY(id)
);

CREATE TABLE employer(
    employer_id SERIAL NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    business character varying,
    phonenumber character varying,
    date timestamp without time zone NOT NULL DEFAULT '2023-06-18 02:52:42.56564'::timestamp without time zone,
    PRIMARY KEY(employer_id)
);

CREATE TABLE employer_payment(
    employer_payment_id SERIAL NOT NULL,
    employer_id integer,
    date character varying(10) NOT NULL,
    paid integer NOT NULL,
    PRIMARY KEY(employer_payment_id),
    CONSTRAINT employer_payment_employer_id_fkey FOREIGN key(employer_id) REFERENCES employer(employer_id)
);

CREATE TABLE employer_record(
    employer_record_id SERIAL NOT NULL,
    employer_id integer,
    date character varying(10) NOT NULL,
    note character varying(255),
    number_worker smallint NOT NULL,
    wage smallint NOT NULL,
    PRIMARY KEY(employer_record_id),
    CONSTRAINT employer_record_employer_id_fkey FOREIGN key(employer_id) REFERENCES employer(employer_id)
);
CREATE TABLE job(
    job_id SERIAL NOT NULL,
    employer_id integer,
    price_id integer,
    title character varying,
    description character varying,
    date character varying(10) NOT NULL,
    PRIMARY KEY(job_id),
    CONSTRAINT job_employer_id_fkey FOREIGN key(employer_id) REFERENCES employer(employer_id),${snap}CONSTRAINT job_price_id_fkey FOREIGN key(price_id) REFERENCES price(price_id)
);

CREATE TABLE payment(
    id SERIAL NOT NULL,
    worker_id integer,
    job_id integer,
    paytype_id integer,
    date timestamp without time zone NOT NULL DEFAULT now(),
    amount numeric NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT payment_worker_id_fkey FOREIGN key(worker_id) REFERENCES worker(worker_id),${snap}CONSTRAINT payment_job_id_fkey FOREIGN key(job_id) REFERENCES job(job_id),${snap}CONSTRAINT payment_paytype_id_fkey FOREIGN key(paytype_id) REFERENCES paytype(id)
);

CREATE TABLE paytype(
    id SERIAL NOT NULL,
    title character varying NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT '2023-06-18 02:43:07.595665'::timestamp without time zone,
    PRIMARY KEY(id)
);

CREATE TABLE price(
    price_id SERIAL NOT NULL,
    fulltime numeric,
    halftime numeric,
    overtime numeric,
    date character varying(10) NOT NULL,
    PRIMARY KEY(price_id)
);

CREATE TABLE worker(
    worker_id SERIAL NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    phone_number character varying,
    date timestamp without time zone NOT NULL DEFAULT '2023-06-18 02:54:09.638472'::timestamp without time zone,
    PRIMARY KEY(worker_id)
);

CREATE TABLE worker_payment(
    worker_payment_id SERIAL NOT NULL,
    worker_id integer,
    employer_id integer,
    date character varying(10) NOT NULL,
    paid integer NOT NULL,
    PRIMARY KEY(worker_payment_id),
    CONSTRAINT worker_payment_worker_id_fkey FOREIGN key(worker_id) REFERENCES worker(worker_id),${snap}CONSTRAINT worker_payment_employer_id_fkey FOREIGN key(employer_id) REFERENCES employer(employer_id)
);

CREATE TABLE worker_record(
    worker_record_id SERIAL NOT NULL,
    worker_id integer,
    employer_id integer,
    date character varying(10) NOT NULL,
    wage smallint NOT NULL,
    PRIMARY KEY(worker_record_id),
    CONSTRAINT worker_record_worker_id_fkey FOREIGN key(worker_id) REFERENCES worker(worker_id),${snap}CONSTRAINT worker_record_employer_id_fkey FOREIGN key(employer_id) REFERENCES employer(employer_id)
);